-- Create medicine_usage table for storing medicine consumption data
CREATE TABLE public.medicine_usage (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  district TEXT NOT NULL,
  sub_district TEXT NOT NULL,
  medicine_name TEXT NOT NULL,
  date DATE NOT NULL,
  quantity_used INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS (allowing public read for this demo - no auth required)
ALTER TABLE public.medicine_usage ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access (no authentication required per spec)
CREATE POLICY "Allow public read access to medicine_usage"
ON public.medicine_usage
FOR SELECT
USING (true);

-- Create index for faster queries
CREATE INDEX idx_medicine_usage_district ON public.medicine_usage(district);
CREATE INDEX idx_medicine_usage_date ON public.medicine_usage(date);
CREATE INDEX idx_medicine_usage_medicine ON public.medicine_usage(medicine_name);

-- Seed the database with simulated sample data
INSERT INTO public.medicine_usage (district, sub_district, medicine_name, date, quantity_used) VALUES
-- District: North Delhi
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '30 days', 1200),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '29 days', 1150),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '28 days', 1180),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '27 days', 1220),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '26 days', 1190),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '25 days', 1210),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '24 days', 1250),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '23 days', 1180),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '22 days', 1200),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '21 days', 1175),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '20 days', 1225),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '19 days', 1190),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '18 days', 1210),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '17 days', 1230),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '16 days', 1185),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '15 days', 1205),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '14 days', 1195),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '13 days', 1220),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '12 days', 1240),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '11 days', 1210),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '10 days', 1185),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '9 days', 1215),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '8 days', 1200),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '7 days', 1180),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '6 days', 1550),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '5 days', 1720),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '4 days', 1850),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '3 days', 1680),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '2 days', 1590),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE - INTERVAL '1 day', 1520),
('North Delhi', 'Civil Lines', 'Paracetamol', CURRENT_DATE, 1480),

-- North Delhi - Karol Bagh - Amoxicillin
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '30 days', 800),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '29 days', 820),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '28 days', 790),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '27 days', 810),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '26 days', 785),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '25 days', 815),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '24 days', 795),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '23 days', 825),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '22 days', 805),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '21 days', 780),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '20 days', 810),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '19 days', 800),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '18 days', 790),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '17 days', 820),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '16 days', 795),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '15 days', 810),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '14 days', 785),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '13 days', 815),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '12 days', 805),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '11 days', 790),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '10 days', 820),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '9 days', 800),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '8 days', 810),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '7 days', 795),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '6 days', 785),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '5 days', 815),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '4 days', 800),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '3 days', 810),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '2 days', 790),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE - INTERVAL '1 day', 805),
('North Delhi', 'Karol Bagh', 'Amoxicillin', CURRENT_DATE, 820),

-- South Delhi - Hauz Khas - Ibuprofen (with spike)
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '30 days', 650),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '29 days', 670),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '28 days', 640),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '27 days', 660),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '26 days', 655),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '25 days', 680),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '24 days', 645),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '23 days', 665),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '22 days', 675),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '21 days', 650),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '20 days', 660),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '19 days', 670),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '18 days', 645),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '17 days', 680),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '16 days', 655),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '15 days', 665),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '14 days', 640),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '13 days', 675),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '12 days', 660),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '11 days', 650),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '10 days', 670),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '9 days', 655),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '8 days', 665),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '7 days', 680),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '6 days', 645),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '5 days', 900),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '4 days', 980),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '3 days', 1050),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '2 days', 920),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE - INTERVAL '1 day', 870),
('South Delhi', 'Hauz Khas', 'Ibuprofen', CURRENT_DATE, 850),

-- South Delhi - Saket - ORS
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '30 days', 450),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '29 days', 470),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '28 days', 440),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '27 days', 460),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '26 days', 455),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '25 days', 480),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '24 days', 445),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '23 days', 465),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '22 days', 475),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '21 days', 450),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '20 days', 460),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '19 days', 470),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '18 days', 445),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '17 days', 480),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '16 days', 455),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '15 days', 465),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '14 days', 440),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '13 days', 475),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '12 days', 460),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '11 days', 450),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '10 days', 470),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '9 days', 455),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '8 days', 465),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '7 days', 480),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '6 days', 445),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '5 days', 460),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '4 days', 470),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '3 days', 455),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '2 days', 475),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE - INTERVAL '1 day', 450),
('South Delhi', 'Saket', 'ORS', CURRENT_DATE, 465),

-- East Delhi - Preet Vihar - Azithromycin (with spike)
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '30 days', 320),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '29 days', 330),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '28 days', 315),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '27 days', 340),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '26 days', 325),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '25 days', 335),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '24 days', 310),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '23 days', 345),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '22 days', 320),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '21 days', 330),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '20 days', 325),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '19 days', 340),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '18 days', 315),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '17 days', 335),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '16 days', 320),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '15 days', 345),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '14 days', 310),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '13 days', 330),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '12 days', 325),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '11 days', 340),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '10 days', 315),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '9 days', 335),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '8 days', 480),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '7 days', 520),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '6 days', 580),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '5 days', 620),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '4 days', 550),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '3 days', 490),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '2 days', 460),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE - INTERVAL '1 day', 420),
('East Delhi', 'Preet Vihar', 'Azithromycin', CURRENT_DATE, 380),

-- East Delhi - Laxmi Nagar - Cetirizine
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '30 days', 550),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '29 days', 560),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '28 days', 545),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '27 days', 570),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '26 days', 555),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '25 days', 565),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '24 days', 540),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '23 days', 575),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '22 days', 550),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '21 days', 560),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '20 days', 555),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '19 days', 570),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '18 days', 545),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '17 days', 565),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '16 days', 550),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '15 days', 575),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '14 days', 540),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '13 days', 560),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '12 days', 555),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '11 days', 570),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '10 days', 545),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '9 days', 565),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '8 days', 550),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '7 days', 575),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '6 days', 540),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '5 days', 560),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '4 days', 555),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '3 days', 570),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '2 days', 545),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE - INTERVAL '1 day', 565),
('East Delhi', 'Laxmi Nagar', 'Cetirizine', CURRENT_DATE, 550),

-- West Delhi - Janakpuri - Metformin
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '30 days', 720),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '29 days', 735),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '28 days', 710),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '27 days', 745),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '26 days', 725),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '25 days', 740),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '24 days', 715),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '23 days', 750),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '22 days', 720),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '21 days', 735),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '20 days', 730),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '19 days', 745),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '18 days', 710),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '17 days', 740),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '16 days', 720),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '15 days', 750),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '14 days', 715),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '13 days', 735),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '12 days', 730),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '11 days', 745),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '10 days', 710),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '9 days', 740),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '8 days', 720),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '7 days', 750),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '6 days', 715),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '5 days', 735),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '4 days', 730),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '3 days', 745),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '2 days', 710),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE - INTERVAL '1 day', 740),
('West Delhi', 'Janakpuri', 'Metformin', CURRENT_DATE, 720),

-- West Delhi - Rajouri Garden - Omeprazole
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '30 days', 420),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '29 days', 430),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '28 days', 415),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '27 days', 440),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '26 days', 425),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '25 days', 435),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '24 days', 410),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '23 days', 445),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '22 days', 420),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '21 days', 430),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '20 days', 425),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '19 days', 440),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '18 days', 415),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '17 days', 435),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '16 days', 420),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '15 days', 445),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '14 days', 410),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '13 days', 430),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '12 days', 425),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '11 days', 440),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '10 days', 415),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '9 days', 435),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '8 days', 420),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '7 days', 445),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '6 days', 410),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '5 days', 430),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '4 days', 425),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '3 days', 440),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '2 days', 415),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE - INTERVAL '1 day', 435),
('West Delhi', 'Rajouri Garden', 'Omeprazole', CURRENT_DATE, 420);